export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_ERROR = 'REGISTER_ERROR';

export const REGISTER_LOADING = 'REGISTER_LOADING';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SAVE_USER_INFO = 'SAVE_USER_INFO';

export const GET_DOCUMENT_LOADING = 'GET_DOCUMENT_LOADING';

export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENT_SUCCESS';

export const GET_DOCUMENT_ERROR = 'GET_DOCUMENT_ERROR';

export const GET_ID_LOADING = 'GET_ID_LOADING';

export const GET_ID_SUCCESS = 'GET_ID_SUCCESS';

export const GET_ID_ERROR = 'GET_ID_ERROR';

export const UPDATE_ID_SUCCESS = 'UPDATE_ID_SUCCESS';

export const ADD_DOCUMENT_LOADING = 'ADD_DOCUMENT_LOADING';

export const ADD_DOCUMENT_SUCCESS = 'ADD_DOCUMENT_SUCCESS';

export const ADD_DOCUMENT_ERROR = 'ADD_DOCUMENT_ERROR';

export const FIRST_VISIT = 'FIRST_VISIT';

export const GET_FOLDER_LOADING = 'GET_FOLDER_LOADING';

export const GET_FOLDER_SUCCESS = 'GET_FOLDER_SUCCESS';

export const GET_FOLDER_ERROR = 'GET_FOLDER_ERROR';

export const GET_FOLDER_ID_LOADING = 'GET_FOLDER_ID_LOADING';

export const GET_FOLDER_ID_SUCCESS = 'GET_FOLDER_ID_SUCCESS';

export const GET_FOLDER_ID_ERROR = 'GET_FOLDER_ID_ERROR';

export const UPDATE_FOLDER_ID_SUCCESS = 'UPDATE_FOLDER_ID_SUCCESS';

export const ADD_FOLDER_LOADING = 'ADD_FOLDER_LOADING';

export const ADD_FOLDER_SUCCESS = 'ADD_FOLDER_SUCCESS';

export const ADD_FOLDER_ERROR = 'ADD_FOLDER_ERROR';

export const FOLDER_FIRST_VISIT = 'FOLDER_FIRST_VISIT';
